/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'transactionsThisMonth' : IDL.Nat,
  'totalPaidAmount' : IDL.Float64,
});
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'provider' : IDL.Text,
  'date' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const PaymentMethod = IDL.Record({
  'id' : PaymentId,
  'owner' : IDL.Principal,
  'cardType' : IDL.Text,
  'cardHolderName' : IDL.Text,
  'cardNumber' : IDL.Text,
});
export const BillPayment = IDL.Record({
  'paymentMethodId' : PaymentId,
  'provider' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaymentMethod' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'removePaymentMethod' : IDL.Func([PaymentId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBillPayment' : IDL.Func([BillPayment], [TransactionId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'transactionsThisMonth' : IDL.Nat,
    'totalPaidAmount' : IDL.Float64,
  });
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'provider' : IDL.Text,
    'date' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const PaymentMethod = IDL.Record({
    'id' : PaymentId,
    'owner' : IDL.Principal,
    'cardType' : IDL.Text,
    'cardHolderName' : IDL.Text,
    'cardNumber' : IDL.Text,
  });
  const BillPayment = IDL.Record({
    'paymentMethodId' : PaymentId,
    'provider' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaymentMethod' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'removePaymentMethod' : IDL.Func([PaymentId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBillPayment' : IDL.Func([BillPayment], [TransactionId], []),
  });
};

export const init = ({ IDL }) => { return []; };